### PR TITLE
modern Hydrogen drumkit format parsing fix

### PR DESCRIPTION
**Pull request by psemiletov**
Currently, DrMr does not parse Hydrogen's kit XML file correctly (the "drumkitComponent" tag is not handled), and modern drumkits are not available. This PR fixes the scan of drum kits and make them available.

### CODE REVIEW

**Comment by falkTX** [comment]
That is nice, thank you!
Does it mean we can load the new kits, and they work as-is?

**Comment by psemiletov** [comment]
Yes, now it can load new kits.
By the way, I've created another fork - Drumrox (https://github.com/psemiletov/drumrox), it will go some away from the DrMr (new mixer with panning laws, sorted kits list, etc.)

**Comment by falkTX** [comment]
> By the way, I've created another fork - Drumrox (https://github.com/psemiletov/drumrox), it will go some away from the DrMr (new mixer with panning laws, sorted kits list, etc.)

yeah I have seen this, good initiative but please give your git commits a message. the git log is impossible to follow right now.

**Comment by psemiletov** [comment]
Commit messages are so boring! There are good old ChangeLog instead, and NEWS file also.

**Comment by falkTX** [comment]
there is no need for a changelog if the commit messages are self-explanatory though. is it that much effort?

**Pull request merged**
